services:
  backend:
    container_name: oncu_backend
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=1453Abdullah*
      - DB_NAME=oncu
      - PORT=8082
      - CORS_ORIGIN=https://imamhatipsporoyunlari.com
      - UPLOAD_DIR=uploads
      - CHOKIDAR_USEPOLLING=false
    volumes:
      - backend:/app
    networks:
      - oncu-wlan
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: oncu_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=https://imamhatipsporoyunlari.com
    depends_on:
      - backend
    ports:
      - 8140:80
    networks:
      - oncu-wlan
    restart: unless-stopped

  db:
    container_name: mysqldb
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1453Abdullah*
      MYSQL_DATABASE: oncu
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=1453Abdullah* --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 40s
    networks:
      - oncu-wlan
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    container_name: oncu_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8054:80
    environment:
      - PMA_HOST=mysqldb
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=1453Abdullah*
      - UPLOAD_LIMIT=300M
      - MEMORY_LIMIT=512M
      - MAX_EXECUTION_TIME=300
    depends_on:
      - db
    networks:
      - oncu-wlan
    restart: unless-stopped

networks:
  oncu-wlan:
    name: oncu-wlan
    driver: bridge

volumes:
  backend:
  db: