services:
  backend:
    container_name: oncu_backend
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - DB_HOST=db  
      - DB_USER=root
      - DB_PASSWORD=1453Abdullah*
      - DB_NAME=oncu
      - PORT=8082
      - CORS_ORIGIN=https://imamhatipsporoyunlari.com
      - UPLOAD_DIR=uploads
      - CHOKIDAR_USEPOLLING=false
    volumes:
      - backend:/app
    networks:
      - oncu-wlan
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    container_name: oncu_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=https://imamhatipsporoyunlari.com
    depends_on:
      - backend
    ports:
      - 8140:80
    networks:
      - oncu-wlan
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    container_name: db  # mysqldb yerine db olarak değiştirildi
    image: mariadb:11.2  # Sürümü belirtmek daha iyi
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --wait_timeout=28800  # Uzun süre beklemesine izin ver
      - --interactive_timeout=28800  # Aynı şekilde
      - --max_allowed_packet=64M
      - --connect_timeout=120
      - --net_read_timeout=120
      - --net_write_timeout=120
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1453Abdullah*
      MYSQL_DATABASE: oncu
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p1453Abdullah*"
        ]
      start_period: 30s
      interval: 20s
      timeout: 30s
      retries: 10
    networks:
      - oncu-wlan
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  oncu-wlan:
    name: oncu-wlan
    driver: bridge

volumes:
  backend:
  frontend:
  db: