services:
  backend:
    container_name: oncu_backend
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=1453Abdullah*
      - DB_NAME=oncu
      - PORT=8082
      - CORS_ORIGIN=https://imamhatipsporoyunlari.com
      - UPLOAD_DIR=uploads
      - CHOKIDAR_USEPOLLING=false
    volumes:
      - backend:/app
    networks:
      - oncu-wlan
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  frontend:
    container_name: oncu_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=https://imamhatipsporoyunlari.com
    depends_on:
      - backend
    ports:
      - 8140:80
    networks:
      - oncu-wlan
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  db:
    container_name: mysqldb
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password --wait_timeout=600 --interactive_timeout=600 --net_read_timeout=300 --net_write_timeout=300 --max_allowed_packet=128M
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1453Abdullah*
      MYSQL_DATABASE: oncu
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      start_period: 30s
      interval: 20s
      timeout: 5m
      retries: 100
    networks:
      - oncu-wlan
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  oncu-wlan:
    name: oncu-wlan
    driver: bridge

volumes:
  backend:
  frontend:
  db: